import { Injectable, NotFoundException } from '@nestjs/common';
import { logger } from '../common/logger/logger.config';
import { PatientsRepository } from '../patients/patients.repository';
import { VisitsRepository } from '../visits/visits.repository';
import { ProceduresRepository } from '../procedures/procedures.repository';
import { MedicationsRepository } from '../medications/medications.repository';
import { EncounterMapper } from './mappers/encounter.mapper';
import { PatientMapper } from './mappers/patient.mapper';
import { ProcedureMapper } from './mappers/procedure.mapper';
import { MedicationMapper } from './mappers/medication.mapper';

/**
 * FHIR Service
 * Business logic for FHIR resource generation
 */
@Injectable()
export class FhirService {
    constructor(
        private readonly patientsRepository: PatientsRepository,
        private readonly visitsRepository: VisitsRepository,
        private readonly proceduresRepository: ProceduresRepository,
        private readonly medicationsRepository: MedicationsRepository,
    ) { }

    /**
     * Get FHIR Patient resource by person ID
     */
    async getPatient(personId: number, baseUrl: string): Promise<any> {
        const person = await this.patientsRepository.findById(personId);
        if (!person) {
            throw new NotFoundException('Patient not found');
        }

        const fhirPatient = PatientMapper.toFhir(person, baseUrl);
        logger.debug({ personId }, 'FHIR Patient resource generated');
        return fhirPatient;
    }

    /**
     * Get FHIR Patient resource by MRN
     */
    async getPatientByMRN(mrn: string, baseUrl: string): Promise<any> {
        const person = await this.patientsRepository.findByMRN(mrn);
        if (!person) {
            throw new NotFoundException('Patient not found');
        }

        const fhirPatient = PatientMapper.toFhir(person, baseUrl);
        logger.debug({ mrn, personId: person.person_id }, 'FHIR Patient resource generated by MRN');
        return fhirPatient;
    }

    /**
     * Get FHIR Encounter resource by visit ID
     */
    async getEncounter(visitId: number, baseUrl: string): Promise<any> {
        const visit = await this.visitsRepository.findById(visitId);
        if (!visit) {
            throw new NotFoundException('Encounter not found');
        }

        const fhirEncounter = EncounterMapper.toFhir(visit, baseUrl);
        logger.debug({ visitId }, 'FHIR Encounter resource generated');
        return fhirEncounter;
    }

    /**
     * Get FHIR Procedure resource by procedure ID
     */
    async getProcedure(procedureId: number, baseUrl: string): Promise<any> {
        const procedure = await this.proceduresRepository.findById(procedureId);
        if (!procedure) {
            throw new NotFoundException('Procedure not found');
        }

        const fhirProcedure = ProcedureMapper.toFhir(procedure, baseUrl);
        logger.debug({ procedureId }, 'FHIR Procedure resource generated');
        return fhirProcedure;
    }

    /**
     * Get FHIR MedicationStatement resource by medication ID
     */
    async getMedication(medicationId: number, baseUrl: string): Promise<any> {
        const medication = await this.medicationsRepository.findById(medicationId);
        if (!medication) {
            throw new NotFoundException('Medication not found');
        }

        const fhirMedication = MedicationMapper.toFhir(medication, baseUrl);
        logger.debug({ medicationId }, 'FHIR MedicationStatement resource generated');
        return fhirMedication;
    }
}

